apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: student-api
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: sre_bootcamp
  DB_SSLMODE: disable
  GIN_MODE: release
  PORT: "8080"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-db-secret
  namespace: student-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: api-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: student-api/db
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: student-api/db
        property: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      nodeSelector:
        type: application
      imagePullSecrets:
        - name: ghcr-pull-secret
      initContainers:
        - name: migrate
          image: ghcr.io/75asu/sre-bootcamp-one2n:0.1.0
          command: ["./migrate"]
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: api-db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-db-credentials
                  key: DB_PASSWORD
      containers:
        - name: student-api
          image: ghcr.io/75asu/sre-bootcamp-one2n:0.1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: api-db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-db-credentials
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
spec:
  type: NodePort
  selector:
    app: student-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
